#!/usr/bin/env ruby

require 'rbtrace'

sidekiq = `which sidekiq` rescue ''

if sidekiq.empty?

  # When we can't locate the Sidekiq executable, mimick
  # its behaviour here.

  require 'sidekiq/cli'

  begin
    cli = Sidekiq::CLI.instance
    cli.parse
    cli.run
  rescue => e
    raise e if $DEBUG
    STDERR.puts e.message
    STDERR.puts e.backtrace.join("\n")
    exit 1
  end

else

  # Otherwise load the sidekiq executable.

  load sidekiq.strip

end
