#!/usr/bin/env ruby

require 'rbtrace'

def sidekiq_bin
  require 'sidekiq/cli'

  begin
    cli = Sidekiq::CLI.instance
    cli.parse
    cli.run
  rescue => e
    raise e if $DEBUG
    STDERR.puts e.message
    STDERR.puts e.backtrace.join("\n")
    exit 1
  end
end

sidekiq = `which sidekiq` rescue ''
if sidekiq.empty?
  # When we can't locate the Sidekiq executable, mimick
  # its behaviour here.
  sidekiq_bin
else
  begin
    # Otherwise load the sidekiq executable.
    load sidekiq.strip
  rescue
    sidekiq_bin
  end
end
